"""Accuracy suite: computed states vs pinned JPL Horizons fixtures.

Fixtures are generated by tools/generate_horizons_fixtures.py and committed;
this suite runs fully offline. Tolerances are per body class and become the
README accuracy table.
"""

import json
import math
import unittest
from pathlib import Path

from orbitarium.core import Orbitarium

FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "horizons"

# body -> (max angular separation deg, max relative distance error,
#          max relative velocity-vector error).
# Set at ~2x the measured worst case over the pinned epochs (floors:
# 0.1 deg, 0.001, 0.002). Planets: consistent with the maximum errors
# Standish publishes for the 1800-2050 fit (largest for Jupiter/Saturn,
# whose mutual perturbations a Kepler fit can't absorb). Moons:
# precessing-ellipse fits to Horizons; the worst cases are the chaotic
# and co-orbital Saturnian moons (Prometheus/Pandora, whose longitudes
# are formally chaotic, and the Janus-Epimetheus horseshoe pair, whose
# sawtooth orbit swaps a two-harmonic libration can only approximate),
# Nereid (solar perturbations on a 360-day, e=0.75 orbit), Mimas
# (Mimas-Tethys libration residual), and Phobos (Mars J2 short-period
# terms).
TOLERANCES = {
    "mercury": (60 / 3600, 0.001, 0.01),   # measured worst:  28", 0.002%, 0.011%
    "venus": (60 / 3600, 0.001, 0.01),     # measured worst:  13", 0.002%, 0.008%
    "earth": (60 / 3600, 0.001, 0.01),     # measured worst:   6", 0.003%, 0.046%
    "mars": (120 / 3600, 0.001, 0.01),     # measured worst:  57", 0.016%, 0.020%
    "jupiter": (600 / 3600, 0.003, 0.01),  # measured worst: 309", 0.070%, 0.156%
    "saturn": (900 / 3600, 0.003, 0.01),   # measured worst: 550", 0.132%, 0.378%
    "uranus": (180 / 3600, 0.003, 0.01),   # measured worst:  79", 0.043%, 0.275%
    "neptune": (90 / 3600, 0.003, 0.01),   # measured worst:  45", 0.022%, 0.296%
    "pluto": (90 / 3600, 0.003, 0.012),    # measured worst:  39", 0.024%, 0.587%
    # moons -------------------------------------------------------------
    "luna": (0.03, 0.0005, 0.001),      # measured worst: 0.015 deg, 0.002%, 0.024%
    "phobos": (5.2, 0.021, 0.062),      # measured worst: 2.57 deg, 1.04%, 3.06%
    "deimos": (0.78, 0.001, 0.015),     # measured worst: 0.39 deg, 0.01%, 0.70%
    "metis": (2.2, 0.0016, 0.036),      # measured worst: 1.07 deg, 0.08%, 1.78%
    "adrastea": (2.1, 0.0013, 0.035),   # measured worst: 1.02 deg, 0.06%, 1.73%
    "amalthea": (1.4, 0.0052, 0.032),   # measured worst: 0.68 deg, 0.26%, 1.56%
    "thebe": (4.9, 0.038, 0.054),       # measured worst: 2.44 deg, 1.85%, 2.66%
    "io": (1.1, 0.0089, 0.019),         # measured worst: 0.52 deg, 0.44%, 0.90%
    "europa": (1.7, 0.019, 0.028),      # measured worst: 0.83 deg, 0.95%, 1.37%
    "ganymede": (0.36, 0.0022, 0.0059), # measured worst: 0.18 deg, 0.11%, 0.29%
    "callisto": (0.13, 0.001, 0.0025),  # measured worst: 0.06 deg, 0.01%, 0.12%
    "pan": (1.1, 0.001, 0.018),         # measured worst: 0.51 deg, 0.00%, 0.88%
    "daphnis": (1.1, 0.001, 0.019),     # measured worst: 0.52 deg, 0.00%, 0.91%
    "atlas": (19.0, 0.0054, 0.33),      # measured worst: 9.43 deg, 0.27%, 16.23%
    "prometheus": (34.0, 0.0043, 0.58), # measured worst: 16.57 deg, 0.21%, 28.70%
    "pandora": (56.0, 0.01, 0.96),      # measured worst: 27.84 deg, 0.50%, 47.79%
    "janus": (18.0, 0.012, 0.31),       # measured worst: 8.95 deg, 0.58%, 15.10%
    "epimetheus": (51.0, 0.048, 0.87),  # measured worst: 25.28 deg, 2.40%, 43.33%
    "aegaeon": (6.8, 0.0015, 0.12),     # measured worst: 3.35 deg, 0.07%, 5.84%
    "mimas": (8.7, 0.027, 0.11),        # measured worst: 4.31 deg, 1.31%, 5.13%
    "methone": (11.0, 0.0054, 0.19),    # measured worst: 5.36 deg, 0.27%, 9.35%
    "anthe": (24.0, 0.008, 0.42),       # measured worst: 11.89 deg, 0.40%, 20.64%
    "pallene": (1.8, 0.0058, 0.026),    # measured worst: 0.89 deg, 0.29%, 1.27%
    "enceladus": (1.3, 0.001, 0.023),   # measured worst: 0.63 deg, 0.01%, 1.11%
    "tethys": (0.39, 0.001, 0.0064),    # measured worst: 0.19 deg, 0.01%, 0.32%
    "telesto": (5.3, 0.001, 0.091),     # measured worst: 2.60 deg, 0.02%, 4.54%
    "calypso": (5.3, 0.0015, 0.092),    # measured worst: 2.61 deg, 0.07%, 4.58%
    "dione": (0.33, 0.001, 0.0055),     # measured worst: 0.16 deg, 0.02%, 0.27%
    "helene": (19.0, 0.028, 0.34),      # measured worst: 9.49 deg, 1.37%, 16.56%
    "polydeuces": (1.1, 0.0016, 0.018), # measured worst: 0.53 deg, 0.08%, 0.89%
    "rhea": (0.2, 0.001, 0.0037),       # measured worst: 0.10 deg, 0.02%, 0.18%
    "titan": (0.12, 0.001, 0.002),      # measured worst: 0.06 deg, 0.02%, 0.08%
    "hyperion": (4.5, 0.065, 0.083),    # measured worst: 2.24 deg, 3.25%, 4.11%
    "iapetus": (0.22, 0.0013, 0.004),   # measured worst: 0.11 deg, 0.06%, 0.20%
    "phoebe": (4.7, 0.038, 0.056),      # measured worst: 2.34 deg, 1.90%, 2.77%
    "cordelia": (1.9, 0.001, 0.031),    # measured worst: 0.91 deg, 0.04%, 1.54%
    "ophelia": (4.7, 0.018, 0.055),     # measured worst: 2.33 deg, 0.88%, 2.75%
    "bianca": (2.9, 0.015, 0.038),      # measured worst: 1.43 deg, 0.71%, 1.89%
    "cressida": (2.0, 0.0095, 0.029),   # measured worst: 0.97 deg, 0.47%, 1.42%
    "desdemona": (2.5, 0.014, 0.034),   # measured worst: 1.24 deg, 0.67%, 1.67%
    "juliet": (1.8, 0.012, 0.027),      # measured worst: 0.88 deg, 0.59%, 1.30%
    "portia": (1.7, 0.0067, 0.025),     # measured worst: 0.84 deg, 0.33%, 1.22%
    "rosalind": (1.4, 0.0053, 0.022),   # measured worst: 0.67 deg, 0.26%, 1.10%
    "cupid": (2.4, 0.0097, 0.029),      # measured worst: 1.17 deg, 0.48%, 1.43%
    "belinda": (0.99, 0.004, 0.017),    # measured worst: 0.49 deg, 0.20%, 0.84%
    "perdita": (1.5, 0.0066, 0.022),    # measured worst: 0.74 deg, 0.33%, 1.10%
    "puck": (2.7, 0.018, 0.029),        # measured worst: 1.31 deg, 0.88%, 1.43%
    "mab": (1.7, 0.01, 0.021),          # measured worst: 0.80 deg, 0.50%, 1.03%
    "miranda": (1.4, 0.001, 0.024),     # measured worst: 0.69 deg, 0.05%, 1.20%
    "ariel": (0.49, 0.0024, 0.0082),    # measured worst: 0.24 deg, 0.12%, 0.41%
    "umbriel": (0.18, 0.0021, 0.0027),  # measured worst: 0.09 deg, 0.10%, 0.13%
    "titania": (0.32, 0.002, 0.0049),   # measured worst: 0.16 deg, 0.10%, 0.24%
    "oberon": (0.28, 0.0025, 0.0042),   # measured worst: 0.14 deg, 0.12%, 0.21%
    "naiad": (2.5, 0.001, 0.043),       # measured worst: 1.25 deg, 0.02%, 2.13%
    "thalassa": (2.3, 0.001, 0.041),    # measured worst: 1.12 deg, 0.02%, 2.03%
    "despina": (1.8, 0.001, 0.031),     # measured worst: 0.88 deg, 0.03%, 1.53%
    "galatea": (1.4, 0.001, 0.024),     # measured worst: 0.69 deg, 0.02%, 1.20%
    "larissa": (1.6, 0.0017, 0.022),    # measured worst: 0.77 deg, 0.08%, 1.06%
    "hippocamp": (0.73, 0.001, 0.018),  # measured worst: 0.36 deg, 0.01%, 0.87%
    "proteus": (1.2, 0.001, 0.016),     # measured worst: 0.58 deg, 0.04%, 0.78%
    "triton": (0.5, 0.001, 0.0072),     # measured worst: 0.25 deg, 0.00%, 0.36%
    "nereid": (10.0, 0.096, 0.12),      # measured worst: 4.99 deg, 4.77%, 5.55%
    "charon": (0.1, 0.001, 0.002),      # measured worst: 0.05 deg, 0.00%, 0.09%
    "styx": (1.2, 0.0067, 0.03),        # measured worst: 0.56 deg, 0.33%, 1.46%
    "nix": (0.58, 0.0068, 0.019),       # measured worst: 0.29 deg, 0.34%, 0.90%
    "kerberos": (0.51, 0.0072, 0.013),  # measured worst: 0.25 deg, 0.36%, 0.61%
    "hydra": (0.22, 0.001, 0.018),      # measured worst: 0.11 deg, 0.03%, 0.87%
}


def norm(v):
    return math.sqrt(sum(c * c for c in v))


def angular_separation_deg(a, b):
    dot = sum(x * y for x, y in zip(a, b))
    cos_angle = max(-1.0, min(1.0, dot / (norm(a) * norm(b))))
    return math.degrees(math.acos(cos_angle))


def find_body(tree, name):
    for body_name, state in tree.items():
        if body_name == name:
            return state
        found = find_body(state.get("orbitals", {}), name)
        if found is not None:
            return found
    return None


class TestAgainstHorizons(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.orbitarium = Orbitarium()

    def test_all_pinned_bodies(self):
        fixtures = sorted(FIXTURE_DIR.glob("*.json"))
        self.assertTrue(fixtures, f"no fixtures found in {FIXTURE_DIR}")
        for path in fixtures:
            fixture = json.loads(path.read_text(encoding="utf-8"))
            body = fixture["body"]
            angle_tol, dist_tol, vel_tol = TOLERANCES[body]
            for record in fixture["states"]:
                with self.subTest(body=body, utc=record["utc"]):
                    tree = self.orbitarium.get_positions(record["utc"])
                    state = find_body(tree, body)
                    self.assertIsNotNone(state, f"{body} missing from tree")

                    computed_pos = (state["x"], state["y"], state["z"])
                    computed_vel = (state["vx"], state["vy"], state["vz"])
                    reference_pos = (record["x_km"], record["y_km"], record["z_km"])
                    reference_vel = (
                        record["vx_km_s"], record["vy_km_s"], record["vz_km_s"],
                    )

                    angle = angular_separation_deg(computed_pos, reference_pos)
                    self.assertLess(
                        angle, angle_tol,
                        f"{body} @ {record['utc']}: {angle * 3600:.1f} arcsec off",
                    )

                    dist_err = abs(norm(computed_pos) - norm(reference_pos)) / norm(reference_pos)
                    self.assertLess(dist_err, dist_tol)

                    vel_err = norm(
                        tuple(c - r for c, r in zip(computed_vel, reference_vel))
                    ) / norm(reference_vel)
                    self.assertLess(vel_err, vel_tol)


if __name__ == "__main__":
    unittest.main()
